function value = supportedAtlases()
  % Return a cell array of supported atlases

  % (C) Copyright 2022 CPP ROI developers
  value = {
           'anatomy_toobox', ...
           'glasser', ...
           'hcpex', ...
           'neuromorphometrics', ...
           'visfatlas', ...
           'wang'};
end
